# Generated by Django 4.1.7 on 2023-03-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('carnetID', models.CharField(max_length=11)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
